name: Publish

on:
  push:
    branches: [ master ]
  
jobs:
  publish:
    name: build, pack & publish
    runs-on: ubuntu-latest
    environment:
      name: main
    steps:
      - uses: actions/checkout@v2

      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.100
      
      - name: tests
        run: dotnet test -c Release

      - name: pack
        run: dotnet pack ./Kasa.Vchasno.Client/Kasa.Vchasno.Client.csproj -c Release -o out -p:PackageVersion=1.0.${{ github.run_number }} --include-symbols --include-source
      
      - name: publush
        run: dotnet nuget push ./out/*.nupkg --source https://api.nuget.org/v3/index.json --api-key ${{secrets.NUGET_ACCESS_TOKEN}} --skip-duplicate
     
