name: test

on:
  workflow_dispatch
  pull_request:
    branches: [ master ]


jobs:
  build-and-test:
    name: run unit tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Setup dotnet
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.100
    
    - name: tests
      run: dotnet test -c Release --logger trx --results-directory out
   
    - name: Test Report
      uses: dorny/test-reporter@v1
      if: success() || failure()
      with:
          name: test run            # Name of the check run which will be created
          path: out/*.trx    
          reporter: dotnet-trx
